version: '3'

services:
  mysql-svc:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gotem_db
      - MYSQL_PASSWORD=root
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"   
    # networks:
    #   - app-network      
      
  # redis-svc:
  #   image: redis:alpine
  #   ports:
  #     - "63790:6379"
  
  # rabbitmq-svc:
  #   image: rabbitmq:3-management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=password
  #   ports:
  #     - "25672:15672"
  #     - "56720:5672"

  gotem:
    image: gotem:latest
    build: .
    env_file:
      - ./.env
    ports:
      - "8080:1323"      
    depends_on:
      - mysql-svc
      # - redis-svc
      # - rabbitmq-svc
    environment:
      - MYSQL_DSN=root:root@tcp(mysql-svc:3306)/gotem_db?parseTime=true&loc=Local&autocommit=1&readTimeout=3s&writeTimeout=3s&multiStatements=true
      # MYSQL_DSN=root:root@tcp(localhost:33060)/gotem_db?parseTime=true&loc=Local&autocommit=1&readTimeout=3s&writeTimeout=3s&multiStatements=true
      - DEVELOPMENT_MODE=true
      - LOG_NAME=gotem.log
    # networks:
    #   - app-network      
    volumes:
      - "./:/go/src/github.com/bondhan/gotem"
    # entrypoint: >
    #   /bin/bash -c "
    #    ./wait-for-it.sh -t 30 mysql-svc:33060 -- echo 'db is up';
    #   "
    # command: ["./wait-for-it.sh", "localhost:33060", "--", "echo", "'db is up'"]
    # entrypoint: >
    #   /bin/bash -c "
    #     echo 'optimistic wait for 15 seconds'
    #     sleep 15;
    #   "

volumes:
    mysql-data:
      