version: '3.4 '

services:
  postgres-svc:
    image: postgres:12.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gotem_db
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 54321:5432         
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080      
      
  redis-svc:
    image: redis:alpine
    ports:
      - "63790:6379"
  
  rabbitmq-svc:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "25672:15672"
      - "56720:5672"

  migrate:
    image: migrate:latest
    build:
      context: .
      dockerfile: Dockerfile-migration
    command: ["/bin/bash", "-c", "/bin/migrate -database postgres://root:root@postgres-svc:5432/gotem_db?sslmode=disable -path /migration/scripts up"]
    volumes:
      - ./migration/scripts:/migration/scripts
    depends_on:
      - postgres-svc
      
  # gotem:
  #   image: gotem:latest
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: "${DOCKER_HEALTHCHECK_TEST:-curl gotem:1323/ping}"
  #     interval: "60s"
  #     timeout: "3s"
  #     start_period: "5s"
  #     retries: 3
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "8080:1323"      
  #   depends_on:
  #     - migrate
  #     - redis-svc
  #     - rabbitmq-svc
  #   volumes:
  #     - "./:/go/src/github.com/bondhan/gotem"
     
volumes:
    postgresql:
    postgresql_data:  