version: '3'

services:
  mysql-svc:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gotem_db
      - MYSQL_PASSWORD=root
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "33060:3306"         
      
  # redis-svc:
  #   image: redis:alpine
  #   ports:
  #     - "6399:6379"
  
  # rabbitmq-svc:
  #   image: rabbitmq:3-management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=password
  #   ports:
  #     - "25672:15672"
  #     - "5622:5672"

  gotem:
    image: gotem:latest
    build: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql-svc
      # - redis-svc
      # - rabbitmq-svc
    volumes:
      - "./:/go/src/github.com/bondhan/gotem"
    # entrypoint: >
    #   /bin/sh -c "
    #    ./wait-for-it.sh mysql-svc:33060 -- echo "db is up";
    #   "
    # entrypoint: >
    #   /bin/sh -c "
    #     wait-for-it.sh 
    #   "
    command: ["./wait-for-it.sh", "mysql-svc:33060", "--", "echo", "db is up"]    

volumes:
    mysql-data:
      