version: '3'

services:
  mysql-svc:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gotem_db
      - MYSQL_PASSWORD=root
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "33060:3306"   
   
  # postgres-svc:
  #   image: postgres:12.1
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=gotem_db
  #   volumes:
  #     - postgresql:/var/lib/postgresql
  #     - postgresql_data:/var/lib/postgresql/data
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8888:8080      
      
  redis-svc:
    image: redis:alpine
    ports:
      - "63790:6379"
  
  rabbitmq-svc:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "25672:15672"
      - "56720:5672"

  gotem:
    image: gotem:latest
    build: .
    env_file:
      - ./.env
    ports:
      - "8080:1323"      
    depends_on:
      - mysql-svc
      - redis-svc
      - rabbitmq-svc
   
    volumes:
      - "./:/go/src/github.com/bondhan/gotem"

volumes:
    mysql-data:
    postgresql:
    postgresql_data:  